# 389DS LDAP Replication Password Manager Configuration
# Example configuration showing predefined password usage
#
# IMPORTANT: Keep this file secure as it contains LDAP credentials!
# Recommended permissions: chmod 600 config-predefined-passwords.yaml

# LDAP Server Configuration
ldap:
  host: "ldap.example.com"
  port: 389
  bind_dn: "cn=Directory Manager"
  password: "your-directory-manager-password"
  base_dn: "cn=config"
  use_tls: false
  skip_tls_verify: false
  timeout: 30

# Password Management - Using Predefined Passwords
password:
  # Random generation settings (used as fallback)
  length: 16
  include_uppercase: true
  include_lowercase: true
  include_numbers: true
  include_special: true
  exclude_chars: "0O1lI"
  
  # EXAMPLE: Predefined passwords for specific agreements
  # These passwords will be used instead of generating random ones
  predefined_passwords:
    agreement-to-consumer1: "Consumer1SecurePass123!"
    agreement-to-consumer2: "Consumer2SecurePass456@"
  
  # Optional: Default password for agreements not listed above
  # default_password: "DefaultReplicationPassword789#"
  
  # Allow random generation as fallback
  generate_random: true

# GRPC Monitoring Configuration
grpc:
  enabled: true
  port: 50051
  log_paths:
    - "/var/log/dirsrv/slapd-ldap/errors"
    - "/var/log/dirsrv/slapd-ldap/access"
  check_interval: 5

# Logging Configuration
logging:
  level: "info"
  file: ""
  timestamps: true
